var equations = [{
    "additions": [{
      "firstNumber": 10,
      "secondNumber": 15,
      "correctResult": 25,
      "incorrectResult1": 30,
      "incorrectResult2": 35
    },{
      "firstNumber": 8,
      "secondNumber": 21,
      "correctResult": 29,
      "incorrectResult1": 28,
      "incorrectResult2": 27
    },{
      "firstNumber": 35,
      "secondNumber": 36,
      "correctResult": 71,
      "incorrectResult1": 61,
      "incorrectResult2": 81
    },{
      "firstNumber": 85,
      "secondNumber": 40,
      "correctResult": 125,
      "incorrectResult1": 124,
      "incorrectResult2": 126
    },{
      "firstNumber": 45,
      "secondNumber": 10,
      "correctResult": 55,
      "incorrectResult1": 65,
      "incorrectResult2": 45
    },{
      "firstNumber": 23,
      "secondNumber": 23,
      "correctResult": 46,
      "incorrectResult1": 43,
      "incorrectResult2": 56
    },{
      "firstNumber": 67,
      "secondNumber": 36,
      "correctResult": 103,
      "incorrectResult1": 93,
      "incorrectResult2": 101
    },{
      "firstNumber": 22,
      "secondNumber": 5,
      "correctResult": 27,
      "incorrectResult1": 24,
      "incorrectResult2": 29
    },{
      "firstNumber": 10,
      "secondNumber": 23,
      "correctResult": 33,
      "incorrectResult1": 13,
      "incorrectResult2": 26
    },{
      "firstNumber": 9,
      "secondNumber": 27,
      "correctResult": 36,
      "incorrectResult1": 34,
      "incorrectResult2": 38
    },{
      "firstNumber": 17,
      "secondNumber": 28,
      "correctResult": 45,
      "incorrectResult1": 48,
      "incorrectResult2": 41
    },{
      "firstNumber": 85,
      "secondNumber": 32,
      "correctResult": 117,
      "incorrectResult1": 107,
      "incorrectResult2": 127
    },{
      "firstNumber": 163,
      "secondNumber": 205,
      "correctResult": 368,
      "incorrectResult1": 356,
      "incorrectResult2": 358
    },{
      "firstNumber": 16,
      "secondNumber": 26,
      "correctResult": 42,
      "incorrectResult1": 44,
      "incorrectResult2": 50
    },{
      "firstNumber": 16,
      "secondNumber": 32,
      "correctResult": 48,
      "incorrectResult1": 46,
      "incorrectResult2": 50
    }, {
      "firstNumber": 29,
      "secondNumber": 21,
      "correctResult": 50,
      "incorrectResult1": 46,
      "incorrectResult2": 52
    }],

    "subtractions": [{
      "firstNumber": 9,
      "secondNumber": 6,
      "correctResult": 3,
      "incorrectResult1": 5,
      "incorrectResult2": 4
    }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }, {
      "firstNumber": 22,
      "secondNumber": 12,
      "correctResult": 10,
      "incorrectResult1": 12,
      "incorrectResult2": 8
      }],
      
    "multiplications": [{
      "firstNumber": 3,
      "secondNumber": 2,
      "correctResult": 6,
      "incorrectResult1": 8,
      "incorrectResult2": 4
    }, {
      "firstNumber": 2,
      "secondNumber": 2,
      "correctResult": 4,
      "incorrectResult1": 2,
      "incorrectResult2": 6
      }],
      
    "divisions": [{
      "firstNumber": 4,
      "secondNumber": 2,
      "correctResult": 2,
      "incorrectResult1": 1,
      "incorrectResult2": 3
    }, {
      "firstNumber": 8,
      "secondNumber": 2,
      "correctResult": 4,
      "incorrectResult1": 3,
      "incorrectResult2": 2
      }]
  }
];